require File.expand_path('../bundle.rb', __FILE__)

bundle 'tomorrow',      'DAddYE/tomorrow.vim'
bundle 'nerdtree',      'scrooloose/nerdtree'
bundle 'nerdtree-tabs', 'jistr/vim-nerdtree-tabs'
bundle 'cmdp',          'kien/ctrlp.vim'
bundle 'powerline',     'Lokaltog/vim-powerline'
bundle 'ack',           'mileszs/ack.vim'
bundle 'haml',          'tpope/vim-haml'
bundle 'slim',          'DAddYE/vim-slim'
bundle 'javascript',    'pangloss/vim-javascript'
bundle 'commentary',    'tpope/vim-commentary'
bundle 'supertab',      'ervandew/supertab'
bundle 'cucumber',      'tpope/vim-cucumber'
bundle 'textile',       'timcharper/textile.vim'
bundle 'snipmate',      'msanders/snipmate.vim'
bundle 'endwise',       'tpope/vim-endwise'
bundle 'coffee',        'kchmck/vim-coffee-script'
bundle 'stylus',        'wavded/vim-stylus'
bundle 'syntastic',     'scrooloose/syntastic'
bundle 'solarized',     'altercation/vim-colors-solarized'
bundle 'fugitive',      'tpope/vim-fugitive'
bundle 'tabular',       'godlygeek/tabular'
bundle 'surround',      'tpope/vim-surround'
bundle 'less.js',       'lunaru/vim-less'
bundle 'task_paper',    'davidoc/taskpaper.vim'
bundle 'minitest',      'sunaku/vim-ruby-minitest'
bundle 'zoomwin',       'blueyed/ZoomWin'
bundle 'jade',          'digitaltoad/vim-jade'
bundle 'tagbar',        'majutsushi/tagbar'
bundle 'vitality',      'sjl/vitality.vim'
bundle 'smart-input',   'kana/vim-smartinput'
bundle 'html5',         'DAddYE/html5.vim'
bundle 'css3',          'hail2u/vim-css3-syntax'
bundle 'nginx',         'andersjanmyr/nginx-vim-syntax'
bundle 'unimpaired',    'tpope/vim-unimpaired'
bundle 'guides',        'nathanaelkane/vim-indent-guides'
bundle 'rails',         'tpope/vim-rails'
bundle 'golang',        'jnwhiteh/vim-golang'
bundle 'scala',         'derekwyatt/vim-scala'

bundle 'ar.snippets' do
  sh 'mkdir -p snippets/ruby'
  sh 'curl -sL https://raw.github.com/DAddYE/snippets/master/active_model.snippets >> snippets/ruby.snippets'
end
